from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import random
import string
import time, datetime, threading
from multiprocessing import Queue
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 820)
        self.BASE = "https://skyzoominteractive.herokuapp.com"
        self.DICTIONARY = {'iata_code': 'municipality', 'DIU': 'Diu', 'AMD': 'Ahmedabad', 'IXU': 'Aurangabad', 'BOM': 'Mumbai', 'BHJ': 'Bhuj', 'IXG': 'Belgaum', 'BDQ': 'Vadodara', 'BHO': 'Bhopal', 'BHU': 'Bhavnagar', 'GOI': 'Vasco da Gama', 'HBX': 'Hubli', 'IDR': 'Indore', 'JLR': 'Jabalpur', 'JGA': 'Jamnagar', 'IXY': 'Kandla', 'HJR': 'Khajuraho', 'KLH': 'Kolhapur', 'NDC': 'Nanded', 'NAG': 'Nagpur', 'ISK': 'Nasik', 'PNQ': 'Pune', 'PBD': 'Porbandar', 'RAJ': 'Rajkot', 'RPR': 'Raipur', 'SAG': 'Shirdi', 'STV': 'Surat', 'UDR': 'Udaipur', 'IXA': 'Agartala', 'IXB': 'Siliguri', 'SHL': 'Shillong', 'BBI': 'Bhubaneswar', 'CCU': 'Kolkata', 'RDP': 'Durgapur', 'GOP': 'Gorakhpur', 'GAU': 'Guwahati', 'GAY': 'Gaya', 'IMF': 'Imphal', 'JRH': 'Jorhat', 'IXS': 'Silchar', 'AJL': 'Aizawl', 'IXI': 'Lilabari', 'DIB': 'Dibrugarh', 'DMU': 'Dimapur', 'PAT': 'Patna', 'IXR': 'Ranchi', 'TEZ': 'Tezpur', 'VTZ': 'Visakhapatnam', 'IXD': 'Allahabad', 'ATQ': 'Amritsar', 'AIP': 'Adampur', 'VNS': 'Varanasi', 'IXC': 'Chandigarh', 'DED': 'Dehradun', 'DEL': 'New Delhi', 'GWL': 'Gwalior', 'JDH': 'Jodhpur', 'JAI': 'Jaipur', 'IXJ': 'Jammu', 'KQH': 'Ajmer', 'IXL': 'Leh', 'LKO': 'Lucknow', 'IXP': 'Pathankot', 'PGH': 'Pantnagar', 'SXR': 'Srinagar', 'TNI': 'Satna', 'LTU': 'Latur', 'TCR': 'Thoothukudi', 'BLR': 'Bangalore', 'VGA': 'Gannavaram', 'CJB': 'Coimbatore', 'COK': 'Kochi', 'CCJ': 'Calicut', 'CDP': 'Kadapa', 'HYD': 'Hyderabad', 'CNN': 'Kannur', 'IXM': 'Madurai', 'IXE': 'Mangalore', 'MAA': 'Chennai', 'IXZ': 'Port Blair', 'RJA': 'Rajahmundry', 'TIR': 'Tirupati', 'TRZ': 'Tiruchirappally', 'TRV': 'Thiruvananthapuram'}
        self.LIST = ['iata_code', 'DIU', 'AMD', 'IXU', 'BOM', 'BHJ', 'IXG', 'BDQ', 'BHO', 'BHU', 'GOI', 'HBX', 'IDR', 'JLR', 'JGA', 'IXY', 'HJR', 'KLH', 'NDC', 'NAG', 'ISK', 'PNQ', 'PBD', 'RAJ', 'RPR', 'SAG', 'STV', 'UDR', 'IXA', 'IXB', 'SHL', 'BBI', 'CCU', 'RDP', 'GOP', 'GAU', 'GAY', 'IMF', 'JRH', 'IXS', 'AJL', 'IXI', 'DIB', 'DMU', 'PAT', 'IXR', 'TEZ', 'VTZ', 'IXD', 'ATQ', 'AIP', 'VNS', 'IXC', 'DED', 'DEL', 'GWL', 'JDH', 'JAI', 'IXJ', 'KQH', 'IXL', 'LKO', 'IXP', 'PGH', 'SXR', 'TNI', 'LTU', 'TCR', 'BLR', 'VGA', 'CJB', 'COK', 'CCJ', 'CDP', 'HYD', 'CNN', 'IXM', 'IXE', 'MAA', 'IXZ', 'RJA', 'TIR', 'TRZ', 'TRV']
        self.Time_pressed = ""
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 801, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.DCODE = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.DCODE.setGeometry(QtCore.QRect(50, 200, 291, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        self.DCODE.setFont(font)
        self.DCODE.setObjectName("Dept")
        self.LCODE = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LCODE.setGeometry(QtCore.QRect(460, 200, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LCODE.setFont(font)
        self.LCODE.setObjectName("Land")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(330, 360, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setObjectName("Month")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 360, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("Day")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(530, 360, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("Year")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 160, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 310, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 310, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 310, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Email = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Email.setGeometry(QtCore.QRect(210, 520, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.Email.setFont(font)
        self.Email.setObjectName("Email")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 470, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 640, 391, 91))
        self.pushButton.clicked.connect(self.clicked)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(213, 160, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 160, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 160, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SKYZoom Interactive!"))
        self.label_2.setText(_translate("MainWindow", "Enter Departure Code"))
        self.label_3.setText(_translate("MainWindow", "Enter Landing Code"))
        self.label_4.setText(_translate("MainWindow", "Day Of Travel"))
        self.label_5.setText(_translate("MainWindow", "Month Of Travel"))
        self.label_6.setText(_translate("MainWindow", "Year Of Travel"))
        self.label_7.setText(_translate("MainWindow", "Email ID"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
    def clicked(self, MainWindow):
        thread = threading.Thread(target=self.clicked_gen, args=[MainWindow])
        thread.start()
    def clicked_gen(self, MainWindow):
        while True:
            DCODE_TEXT = self.DCODE.toPlainText().upper()
            LCODE_TEXT = self.LCODE.toPlainText().upper()
            DAY_TEXT = int(self.plainTextEdit.toPlainText())
            MONTH_TEXT = int(self.plainTextEdit_3.toPlainText())
            YEAR_TEXT = int(self.plainTextEdit_2.toPlainText())
            EMAIL_TEXT = self.Email.toPlainText()
            PRESENT1 = False
            PRESENT2 = False
            for i in self.LIST:
                if i == LCODE_TEXT:
                    PRESENT1 = True
            for j in self.LIST:
                if j == DCODE_TEXT:
                    PRESENT2 = True 
            if PRESENT1 & PRESENT2:
                letters = string.ascii_lowercase
                result_str = ''.join(random.choice(letters) for i in range(10))
                res = requests.get(self.BASE + f"{DCODE_TEXT}/{LCODE_TEXT}/{DAY_TEXT}/{MONTH_TEXT}/{YEAR_TEXT}/{EMAIL_TEXT}/{result_str}")
                print(res.json())
            else: 
                print("A Problem Occured! (May Have Entered The Wrong Departure and/or Landing Code.)")
            print(DCODE_TEXT)
            print(LCODE_TEXT)
            print(DAY_TEXT)
            print(MONTH_TEXT)
            print(YEAR_TEXT)
            
            time.sleep(3700)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())